/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletsRouteImport } from './routes/wallets'
import { Route as StrategyRouteImport } from './routes/strategy'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as SharpRouteImport } from './routes/sharp'
import { Route as ShadowRouteImport } from './routes/shadow'
import { Route as RuntimeRouteImport } from './routes/runtime'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CanonicalRouteImport } from './routes/canonical'
import { Route as BotRouteImport } from './routes/bot'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SharpMarketConditionIdRouteImport } from './routes/sharp.market.$conditionId'

const WalletsRoute = WalletsRouteImport.update({
  id: '/wallets',
  path: '/wallets',
  getParentRoute: () => rootRouteImport,
} as any)
const StrategyRoute = StrategyRouteImport.update({
  id: '/strategy',
  path: '/strategy',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const SharpRoute = SharpRouteImport.update({
  id: '/sharp',
  path: '/sharp',
  getParentRoute: () => rootRouteImport,
} as any)
const ShadowRoute = ShadowRouteImport.update({
  id: '/shadow',
  path: '/shadow',
  getParentRoute: () => rootRouteImport,
} as any)
const RuntimeRoute = RuntimeRouteImport.update({
  id: '/runtime',
  path: '/runtime',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CanonicalRoute = CanonicalRouteImport.update({
  id: '/canonical',
  path: '/canonical',
  getParentRoute: () => rootRouteImport,
} as any)
const BotRoute = BotRouteImport.update({
  id: '/bot',
  path: '/bot',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SharpMarketConditionIdRoute = SharpMarketConditionIdRouteImport.update({
  id: '/market/$conditionId',
  path: '/market/$conditionId',
  getParentRoute: () => SharpRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bot': typeof BotRoute
  '/canonical': typeof CanonicalRoute
  '/login': typeof LoginRoute
  '/runtime': typeof RuntimeRoute
  '/shadow': typeof ShadowRoute
  '/sharp': typeof SharpRouteWithChildren
  '/stats': typeof StatsRoute
  '/strategy': typeof StrategyRoute
  '/wallets': typeof WalletsRoute
  '/sharp/market/$conditionId': typeof SharpMarketConditionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bot': typeof BotRoute
  '/canonical': typeof CanonicalRoute
  '/login': typeof LoginRoute
  '/runtime': typeof RuntimeRoute
  '/shadow': typeof ShadowRoute
  '/sharp': typeof SharpRouteWithChildren
  '/stats': typeof StatsRoute
  '/strategy': typeof StrategyRoute
  '/wallets': typeof WalletsRoute
  '/sharp/market/$conditionId': typeof SharpMarketConditionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bot': typeof BotRoute
  '/canonical': typeof CanonicalRoute
  '/login': typeof LoginRoute
  '/runtime': typeof RuntimeRoute
  '/shadow': typeof ShadowRoute
  '/sharp': typeof SharpRouteWithChildren
  '/stats': typeof StatsRoute
  '/strategy': typeof StrategyRoute
  '/wallets': typeof WalletsRoute
  '/sharp/market/$conditionId': typeof SharpMarketConditionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bot'
    | '/canonical'
    | '/login'
    | '/runtime'
    | '/shadow'
    | '/sharp'
    | '/stats'
    | '/strategy'
    | '/wallets'
    | '/sharp/market/$conditionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bot'
    | '/canonical'
    | '/login'
    | '/runtime'
    | '/shadow'
    | '/sharp'
    | '/stats'
    | '/strategy'
    | '/wallets'
    | '/sharp/market/$conditionId'
  id:
    | '__root__'
    | '/'
    | '/bot'
    | '/canonical'
    | '/login'
    | '/runtime'
    | '/shadow'
    | '/sharp'
    | '/stats'
    | '/strategy'
    | '/wallets'
    | '/sharp/market/$conditionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BotRoute: typeof BotRoute
  CanonicalRoute: typeof CanonicalRoute
  LoginRoute: typeof LoginRoute
  RuntimeRoute: typeof RuntimeRoute
  ShadowRoute: typeof ShadowRoute
  SharpRoute: typeof SharpRouteWithChildren
  StatsRoute: typeof StatsRoute
  StrategyRoute: typeof StrategyRoute
  WalletsRoute: typeof WalletsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallets': {
      id: '/wallets'
      path: '/wallets'
      fullPath: '/wallets'
      preLoaderRoute: typeof WalletsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strategy': {
      id: '/strategy'
      path: '/strategy'
      fullPath: '/strategy'
      preLoaderRoute: typeof StrategyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sharp': {
      id: '/sharp'
      path: '/sharp'
      fullPath: '/sharp'
      preLoaderRoute: typeof SharpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shadow': {
      id: '/shadow'
      path: '/shadow'
      fullPath: '/shadow'
      preLoaderRoute: typeof ShadowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runtime': {
      id: '/runtime'
      path: '/runtime'
      fullPath: '/runtime'
      preLoaderRoute: typeof RuntimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canonical': {
      id: '/canonical'
      path: '/canonical'
      fullPath: '/canonical'
      preLoaderRoute: typeof CanonicalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bot': {
      id: '/bot'
      path: '/bot'
      fullPath: '/bot'
      preLoaderRoute: typeof BotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sharp/market/$conditionId': {
      id: '/sharp/market/$conditionId'
      path: '/market/$conditionId'
      fullPath: '/sharp/market/$conditionId'
      preLoaderRoute: typeof SharpMarketConditionIdRouteImport
      parentRoute: typeof SharpRoute
    }
  }
}

interface SharpRouteChildren {
  SharpMarketConditionIdRoute: typeof SharpMarketConditionIdRoute
}

const SharpRouteChildren: SharpRouteChildren = {
  SharpMarketConditionIdRoute: SharpMarketConditionIdRoute,
}

const SharpRouteWithChildren = SharpRoute._addFileChildren(SharpRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BotRoute: BotRoute,
  CanonicalRoute: CanonicalRoute,
  LoginRoute: LoginRoute,
  RuntimeRoute: RuntimeRoute,
  ShadowRoute: ShadowRoute,
  SharpRoute: SharpRouteWithChildren,
  StatsRoute: StatsRoute,
  StrategyRoute: StrategyRoute,
  WalletsRoute: WalletsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
